{% set version = '0.1.4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pryr
  version: {{ version|replace("-", "_") }}

source:
  fn: pryr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/pryr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pryr/pryr_{{ version }}.tar.gz
  sha256: d39834316504c49ecd4936cbbcaf3ee3dae6ded287af42475bf38c9e682f721b

build:
  merge_build_host: True  # [win]
  number: 2
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.11.0
    - r-codetools
    - r-stringr
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.11.0
    - r-codetools
    - r-stringr

test:
  commands:
    - $R -e "library('pryr')"           # [not win]
    - "\"%R%\" -e \"library('pryr')\""  # [win]

about:
  home: https://github.com/hadley/pryr
  license: GPL-2
  summary: Useful tools to pry back the covers of R and understand the language at a deeper level.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
