{% set version = "0.1.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pryr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pryr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pryr/pryr_{{ version }}.tar.gz
  sha256: 7b1653ec51850f4633cee8e2eb7d0b2724fb587b801539488b426cf88f0f770b

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=0.11.0
    - r-codetools
    - r-lobstr
    - r-stringr
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.11.0
    - r-codetools
    - r-lobstr
    - r-stringr

test:
  commands:
    - $R -e "library('pryr')"           # [not win]
    - "\"%R%\" -e \"library('pryr')\""  # [win]

about:
  home: https://github.com/hadley/pryr
  license: GPL-2.0-only
  summary: Useful tools to pry back the covers of R and understand the language at a deeper level.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
