travis:
  secure:
    BINSTAR_TOKEN: FCFvh3VwXJX6x4i0A5facggxgTIA7sgRiw8WkeAR3p2hTULUL13DAl0gM0FdMsL45KeDabgk9RpZvGx5TQDRH9h9ycTOa0qDj9wNmYbcSwkSAinDR5ewjRTnEDpkBZFLcgOPIz1wL0xT425sfOEO/2hwbOiI3qvRaC+vt0nKZ14OQvuvZ2pp2LeaSPVzhP7Zk3YwUTZlCV/d6TagXiTkGifNayCIeaSXrHuUSU8nPX4A1w01Gc1Upxmed8iK9cm0KFdZ22pb1eKuv5FtMFX2HTXYSGQI6I7QczqRACDnhGbIDOyUVZfTyVvvrgUdNxSXOW377xb1DlwgUOJUIJsKCcbY26MnlakW8DtTW9VGWzbjQEUwk7SHS/b9tmXCJvXBY0S24lMk/MPEo6s1ztLX/Wn+hQUw5YKRWte030p6t0l6piHnYh6PulOJAHpAkZYdpejnxth1FaqtLBWkODdPpSc+qjENrvo938JId++ZmOALAjmVVOirW4s3LMnJtxEtKF9shKdxSjhhOMBlPjGyBUn8kqpADNXajNQ8dFf2QmOVczVrLfDFFpNXLkjFo+igLHT5mztpcglp3DeLt/UUidxrz/+675cgjBdx7iBHOVl23ll+gc9N44ADVRIHVQLdjNPbajzCmt2zXYJdI/VmeTqeMNB+Be69X6K2hfIPsRs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
